In [2]:
import os
import pandas as pd
import geopandas as gpd

from pathlib import Path
from sqlalchemy import create_engine, text
from geoalchemy2 import Geometry

In [3]:
#| echo: true

DATA_DIR = Path("../data/citibike/JC")

citibike_path = DATA_DIR / "JC2025_Enriched.csv"
weather_path = DATA_DIR / "jersey_weather_2025.csv"
neighborhood_path = DATA_DIR / "jersey-city-neighborhoods.geojson"


# print(citibike_path.exists(), citibike_path)
# print(weather_path.exists(), weather_path)
# print(neighborhood_path.exists(), neighborhood_path)

In [26]:
#| echo: true

DB_USER = "postgres"
DB_PASSWORD = "password"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "citibike"

DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)


DATABASE_URL

'postgresql+psycopg2://postgres:password@localhost:5432/citibike'

In [5]:
#| echo: true
#| eval: false

DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")
DB_NAME = os.getenv("DB_NAME")

DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

In [6]:
engine = create_engine(DATABASE_URL)

engine

Engine(postgresql+psycopg2://postgres:***@localhost:5432/citibike)

In [7]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT version();"))
    print(result.fetchone()[0])

PostgreSQL 17.0 (Debian 17.0-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

In [8]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT PostGIS_Version();"))
    print(result.fetchone()[0])

3.4 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

In [19]:
citibike_df = pd.read_csv(citibike_path)

citibike_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_duration_minutes,date,month,month_name,day_of_week,hour,season
0,880A0159BA5275FB,electric_bike,2025-01-16 17:50:49.136,2025-01-16 17:57:00.710,Hilltop,JC019,Pershing Field,JC024,40.731169,-74.057574,40.742677,-74.051789,member,6.192900,2025-01-16,2025-01,January,Thursday,17,Winter
1,1A5E1E274B2AF0AD,electric_bike,2025-01-31 06:10:41.818,2025-01-31 06:22:09.499,Hilltop,JC019,Jackson Square,JC063,40.731169,-74.057574,40.711130,-74.078900,member,11.461350,2025-01-31,2025-01,January,Friday,6,Winter
2,EA9928D3C05B8377,classic_bike,2025-01-09 16:42:50.213,2025-01-09 17:04:12.870,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member,21.377617,2025-01-09,2025-01,January,Thursday,16,Winter
3,3C42C367750B9292,electric_bike,2025-01-21 16:14:14.398,2025-01-21 16:37:10.458,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member,22.934333,2025-01-21,2025-01,January,Tuesday,16,Winter
4,94D3B0265A7BDE1F,classic_bike,2025-01-30 16:38:18.840,2025-01-30 17:04:08.166,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member,25.822100,2025-01-30,2025-01,January,Thursday,16,Winter

In [33]:
citibike_df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'ride_duration_minutes', 'date', 'month', 'month_name',
       'day_of_week', 'hour', 'season'],
      dtype='str')

In [34]:
citibike_df["started_at"] = pd.to_datetime(
    citibike_df["started_at"],
    errors="coerce"
)

citibike_df["ended_at"] = pd.to_datetime(
    citibike_df["ended_at"],
    errors="coerce"
)

In [35]:
citibike_df["ride_date"] = citibike_df["started_at"].dt.date

citibike_df["ride_date"] = pd.to_datetime(
    citibike_df["ride_date"],
    errors="coerce"
)

In [36]:
citibike_df[
    [
        "ride_id",
        "started_at",
        "ended_at",
        "ride_date"
    ]
].head()

            ride_id              started_at                ended_at  ride_date
0  880A0159BA5275FB 2025-01-16 17:50:49.136 2025-01-16 17:57:00.710 2025-01-16
1  1A5E1E274B2AF0AD 2025-01-31 06:10:41.818 2025-01-31 06:22:09.499 2025-01-31
2  EA9928D3C05B8377 2025-01-09 16:42:50.213 2025-01-09 17:04:12.870 2025-01-09
3  3C42C367750B9292 2025-01-21 16:14:14.398 2025-01-21 16:37:10.458 2025-01-21
4  94D3B0265A7BDE1F 2025-01-30 16:38:18.840 2025-01-30 17:04:08.166 2025-01-30

In [37]:
citibike_df.to_sql(
    name="jersey_city",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=50_000,
    method="multi"
)

3007860

In [38]:
citibike_path

WindowsPath('../data/citibike/JC/JC2025_Enriched.csv')

In [39]:
citibike_df.shape

(3007860, 21)

In [40]:
query = """
SELECT * 
FROM jersey_city
LIMIT 10;
"""

pd.read_sql(query, con=engine)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,end_lng,member_casual,ride_duration_minutes,date,month,month_name,day_of_week,hour,season,ride_date
0,880A0159BA5275FB,electric_bike,2025-01-16 17:50:49.136,2025-01-16 17:57:00.710,Hilltop,JC019,Pershing Field,JC024,40.731169,-74.057574,...,-74.051789,member,6.192900,2025-01-16,2025-01,January,Thursday,17,Winter,2025-01-16
1,1A5E1E274B2AF0AD,electric_bike,2025-01-31 06:10:41.818,2025-01-31 06:22:09.499,Hilltop,JC019,Jackson Square,JC063,40.731169,-74.057574,...,-74.078900,member,11.461350,2025-01-31,2025-01,January,Friday,6,Winter,2025-01-31
2,EA9928D3C05B8377,classic_bike,2025-01-09 16:42:50.213,2025-01-09 17:04:12.870,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,...,-74.030305,member,21.377617,2025-01-09,2025-01,January,Thursday,16,Winter,2025-01-09
3,3C42C367750B9292,electric_bike,2025-01-21 16:14:14.398,2025-01-21 16:37:10.458,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,...,-74.030305,member,22.934333,2025-01-21,2025-01,January,Tuesday,16,Winter,2025-01-21
4,94D3B0265A7BDE1F,classic_bike,2025-01-30 16:38:18.840,2025-01-30 17:04:08.166,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,...,-74.030305,member,25.822100,2025-01-30,2025-01,January,Thursday,16,Winter,2025-01-30
5,9F58D1A2D274211B,electric_bike,2025-01-26 12:41:21.306,2025-01-26 12:50:06.079,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,...,-74.030305,member,8.746217,2025-01-26,2025-01,January,Sunday,12,Winter,2025-01-26
6,06E081ED7FFC3B9A,electric_bike,2025-01-14 07:46:19.544,2025-01-14 07:54:25.887,Hilltop,JC019,Morris Canal,JC072,40.731169,-74.057574,...,-74.038526,member,8.105717,2025-01-14,2025-01,January,Tuesday,7,Winter,2025-01-14
7,A2933F641B0B4756,electric_bike,2025-01-01 17:28:06.205,2025-01-01 17:35:36.233,Hilltop,JC019,Glenwood Ave,JC094,40.731169,-74.057574,...,-74.071061,member,7.500467,2025-01-01,2025-01,January,Wednesday,17,Winter,2025-01-01
8,5A29AAD1161A2DC7,electric_bike,2025-01-13 12:33:51.980,2025-01-13 12:58:04.250,4 St & River St,HB611,Clinton St & Grand St,5303.06,40.740814,-74.027406,...,-73.987030,casual,24.204500,2025-01-13,2025-01,January,Monday,12,Winter,2025-01-13
9,598F2567309571D5,electric_bike,2025-01-05 19:10:58.189,2025-01-05 19:18:46.106,Dixon Mills,JC076,Pershing Field,JC024,40.721630,-74.049968,...,-74.051789,member,7.798617,2025-01-05,2025-01,January,Sunday,19,Winter,2025-01-05

Load Weather Data

In [41]:
weather_df = pd.read_csv(weather_path)

weather_df.head()

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,11.0,3.9,7.4,4.5,4.5,0.0,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.0,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.0,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1,2025-01-04
4,0.4,-3.6,-2.2,0.0,0.0,0.0,19.9,2025-01-05

In [45]:
#| echo: true

weather_df["date"] = pd.to_datetime(
    weather_df["date"],
    errors="coerce"
)

weather_df.head()

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,11.0,3.9,7.4,4.5,4.5,0.0,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.0,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.0,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1,2025-01-04
4,0.4,-3.6,-2.2,0.0,0.0,0.0,19.9,2025-01-05

In [44]:
#| echo: true

weather_df.to_sql(
    name="jersey_weather",
    con=engine,
    if_exists="replace",
    index=False
)

365

In [10]:
query = """
SELECT
    *
FROM jersey_weather
LIMIT 10;
"""

pd.read_sql(
    query,
    con=engine
)

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,11.0,3.9,7.4,4.5,4.5,0.00,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.00,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.00,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.00,26.1,2025-01-04
4,0.4,-3.6,-2.2,0.0,0.0,0.00,19.9,2025-01-05
5,-1.6,-4.5,-2.3,1.7,0.0,1.19,16.7,2025-01-06
6,-3.0,-8.7,-5.2,0.0,0.0,0.00,29.9,2025-01-07
7,-2.5,-6.6,-4.3,0.0,0.0,0.00,25.4,2025-01-08
8,-1.5,-6.8,-4.2,0.0,0.0,0.00,29.0,2025-01-09
9,3.3,-3.9,-0.9,0.0,0.0,0.00,22.5,2025-01-10

Load Neighborhood GeoJSON as Spatial Table

In [9]:
#| echo: true

neighborhood_gdf = gpd.read_file(neighborhood_path)

neighborhood_gdf.head()

,geo_point_2d,cartodb_id,area_sq_ft,acres,area,neighborho,color,geometry
0,"{'lon': -74.034926976, 'lat': 40.7292547932}",12,411601381.8,9449.068,Downtown,Newport,22.0,"POLYGON ((-74.03709 40.73404, -74.03062 40.733..."
1,"{'lon': -74.0623580331, 'lat': 40.6991894289}",52,411601381.8,9449.068,Bergen-Lafayette,LSP Industrial,NaN,"POLYGON ((-74.06808 40.69684, -74.06862 40.700..."
2,"{'lon': -74.0745396393, 'lat': 40.6942023599}",38,411601381.8,9449.068,Greenville,Port Liberte,NaN,"POLYGON ((-74.06862 40.70098, -74.06808 40.696..."
3,"{'lon': -74.0612789066, 'lat': 40.7126760382}",35,411601381.8,9449.068,Bergen-Lafayette,Lafayette,12.0,"POLYGON ((-74.056 40.71735, -74.056 40.71692, ..."
4,"{'lon': -74.0855031402, 'lat': 40.7007912121}",51,411601381.8,9449.068,Greenville,Jackson Hill,15.0,"POLYGON ((-74.07561 40.70233, -74.0758 40.7020..."

In [11]:
#| echo: true

neighborhood_gdf.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [12]:
#| echo: true

neighborhood_gdf.geom_type.value_counts()

Polygon    53
Name: count, dtype: int64

In [13]:
#| echo: true

neighborhood_gdf.to_postgis(
    name="jersey_city_neighborhoods",
    con=engine,
    if_exists="replace",
    index=False
)

In [17]:
query = """
SELECT
    neighborhood,
    ST_GeometryType(geometry) AS geometry_type,
    ST_SRID(geometry) AS srid
FROM jersey_city_neighborhoods
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

     neighborhood geometry_type  srid
0         Newport    ST_Polygon  4326
1  LSP Industrial    ST_Polygon  4326
2    Port Liberte    ST_Polygon  4326
3       Lafayette    ST_Polygon  4326
4    Jackson Hill    ST_Polygon  4326

In [ ]:

#| echo: true

start_stations = citibike_df[
    [
        "ride_id",
        "start_station_id",
        "start_station_name",
        "start_lat",
        "start_lng"
    ]
].copy()

start_stations = start_stations.rename(
    columns={
        "start_station_id": "station_id",
        "start_station_name": "station_name",
        "start_lat": "lat",
        "start_lng": "lng"
    }
)

start_stations["activity_type"] = "departure"

In [21]:
#| echo: true

end_stations = citibike_df[
    [
        "ride_id",
        "end_station_id",
        "end_station_name",
        "end_lat",
        "end_lng"
    ]
].copy()

end_stations = end_stations.rename(
    columns={
        "end_station_id": "station_id",
        "end_station_name": "station_name",
        "end_lat": "lat",
        "end_lng": "lng"
    }
)

end_stations["activity_type"] = "arrival"

In [22]:
#| echo: true

station_activity_long = pd.concat(
    [
        start_stations,
        end_stations
    ],
    ignore_index=True
)

station_activity_long = station_activity_long.dropna(
    subset=[
        "station_id",
        "station_name",
        "lat",
        "lng"
    ]
)

In [23]:
#| echo: true

station_activity_agg = (
    station_activity_long
    .groupby(
        [
            "station_id",
            "station_name",
            "lat",
            "lng",
            "activity_type"
        ],
        as_index=False
    )
    .agg(
        number_of_rides=("ride_id", "count")
    )
)

In [24]:
#| echo: true

station_summary = (
    station_activity_agg
    .pivot_table(
        index=[
            "station_id",
            "station_name",
            "lat",
            "lng"
        ],
        columns="activity_type",
        values="number_of_rides",
        fill_value=0
    )
    .reset_index()
)

station_summary.columns.name = None

station_summary = station_summary.rename(
    columns={
        "departure": "total_departures",
        "arrival": "total_arrivals"
    }
)

if "total_departures" not in station_summary.columns:
    station_summary["total_departures"] = 0

if "total_arrivals" not in station_summary.columns:
    station_summary["total_arrivals"] = 0

station_summary["total_activity"] = (
    station_summary["total_departures"] +
    station_summary["total_arrivals"]
)

station_summary["net_departures"] = (
    station_summary["total_departures"] -
    station_summary["total_arrivals"]
)

station_summary = station_summary.sort_values(
    "total_activity",
    ascending=False
).reset_index(drop=True)

station_summary.head()

,station_id,station_name,lat,lng,total_arrivals,total_departures,total_activity,net_departures
0,JC115,Grove St PATH,40.719410,-74.043090,143749.0,135136.0,278885.0,-8613.0
1,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,79808.0,77422.0,157230.0,-2386.0
2,JC009,Hamilton Park,40.727596,-74.044247,67368.0,66940.0,134308.0,-428.0
3,HB106,River St & Newark St,40.736722,-74.029007,66339.0,64149.0,130488.0,-2190.0
4,JC066,Newport PATH,40.727224,-74.033759,63103.0,62825.0,125928.0,-278.0

Convert Station Summary to GeoDataFrame

In [25]:
#| echo: true

station_gdf = gpd.GeoDataFrame(
    station_summary,
    geometry=gpd.points_from_xy(
        station_summary["lng"],
        station_summary["lat"]
    ),
    crs="EPSG:4326"
)

station_gdf.head()

,station_id,station_name,lat,lng,total_arrivals,total_departures,total_activity,net_departures,geometry
0,JC115,Grove St PATH,40.719410,-74.043090,143749.0,135136.0,278885.0,-8613.0,POINT (-74.04309 40.71941)
1,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,79808.0,77422.0,157230.0,-2386.0,POINT (-74.0303 40.73594)
2,JC009,Hamilton Park,40.727596,-74.044247,67368.0,66940.0,134308.0,-428.0,POINT (-74.04425 40.7276)
3,HB106,River St & Newark St,40.736722,-74.029007,66339.0,64149.0,130488.0,-2190.0,POINT (-74.02901 40.73672)
4,JC066,Newport PATH,40.727224,-74.033759,63103.0,62825.0,125928.0,-278.0,POINT (-74.03376 40.72722)

Write Station Points to PostGIS

In [ ]:
station_gdf.to_postgis(
    name="jc_2025_stations",
    con=engine,
    if_exists="replace",
    index=False
)

In [27]:
#| echo: true

query = """
SELECT
    station_id,
    station_name,
    total_activity,
    ST_GeometryType(geometry) AS geometry_type,
    ST_SRID(geometry) AS srid
FROM jc_2025_stations
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

,station_id,station_name,total_activity,geometry_type,srid
0,JC115,Grove St PATH,278885.0,ST_Point,4326
1,HB101,Hoboken Terminal - Hudson St & Hudson Pl,157230.0,ST_Point,4326
2,JC009,Hamilton Park,134308.0,ST_Point,4326
3,HB106,River St & Newark St,130488.0,ST_Point,4326
4,JC066,Newport PATH,125928.0,ST_Point,4326